services:
  - type: web
    name: n8n-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "http"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: WEBHOOK_URL
        value: "https://n8nproject-1.onrender.com/"
    # Add these environment variables manually in Render dashboard:
    # N8N_BASIC_AUTH_USER=your-username
    # N8N_BASIC_AUTH_PASSWORD=your-password  
    # GEMINI_API_KEY=your-api-key
