services:
  - type: web
    name: n8n-app
    runtime: docker
    dockerfilePath: ./dockerfile
    plan: free
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "http"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "adminpassword"
      - key: WEBHOOK_URL
        value: "https://your-app-name.onrender.com/"
      - key: GEMINI_API_KEY
        value: "AIzaSyApeU7dGzKFodIYkqOUOM0-SetHQ-jVPXI"
