services:
  - type: web
    name: gemini-pitch-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    envVars:
      - key: PORT
        value: "5678"
      - key: NODE_ENV
        value: "production"
      - key: GEMINI_API_KEY
        value: "AIzaSyApeU7dGzKFodIYkqOUOM0-SetHQ-jVPXI"
    # Health check endpoint
    healthCheckPath: /
